MBII/TextAssets

- MBAssets3/ext_data/sabers/saber_hilts_Open1.sab
Added:
- A'Sharad Hett's Lightsabers
- Darth Malgus (Damaged)
- Darth Revan (TOR)
- Darth Sion
- Galen Marek (Ceremonial Jedi Robes)
> Added new hilts by Doughnuts

- MBAssets3/ext_data/sabers/saber_hilts_Open2.sab
Additions:
- Jocasta Nu
- Lord Kallig
- Mara Jade (Emperor's Hand)
- Orgus Din
- Rosh Penin
- Tavion Axmis
- Thexan
- Tulak Hord
- Turanis
- Zayne Carrick
Updated:
- Darth Malgus
- Satele Shan
- Sith Stalker
> Added new hilts by Doughnuts - Part 2

- mb2_cmp_assets3/ext_data/mb2/character/Arena_Stass.mbch
Re-added missing mbch that was causing issues
> Missing mbch

- mb2_cmp_assets3/ext_data/mb2/character/Arena_Stass.mbch
was missing and causing issues
> mbch re-added

- MBAssets3/models/players/gwethenea/model_rebel_tan.skin
- MBAssets3/models/players/rebel_gag/modeldata.cfg
> Rebel Grenadier soldier variant // Rebel Militia soundset

- MBAssets3/models/players/rebel_r1/model_urban.skin
- MBAssets3/models/players/trandoshan/model_blue.skin
- MBAssets3/models/players/trandoshan/model_default.skin
- MBAssets3/models/players/trandoshan/model_merc.skin
- MBAssets3/models/players/trandoshan/model_red.skin
- MBAssets3/models/players/trandoshan/model_rgb.skin
- MBAssets3/models/players/trandoshan/model_sp.skin
- MBAssets3/models/players/trandoshan/model_tra1.skin
- MBAssets3/models/players/trandoshan/model_tra2.skin
- MBAssets3/models/players/trandoshan/model_tra3.skin
- MBAssets3/models/players/trandoshan/model_tra4.skin
- MBAssets3/shaders/rebels.shader
2nd variant for Rogue One trooper
trando skin tweaks
> Helmet shader for 2nd variant of Rogue One trooper

- MBAssets3/ext_data/mb2/character/bs_r_commander.mbch
- MBAssets3/ext_data/vehicles/dxun_g0t0.veh
- MBAssets3/models/players/luke_ceremonial/model_default.skin
- MBAssets3/models/players/luke_rotj/model_tm.skin
- MBAssets3/models/players/rebel_commando/model_duros_ctf2.skin
- MBAssets3/models/players/rebel_commando/model_nikto.skin
- MBAssets3/models/players/stormie_hero/model_default.skin
- MBAssets3/models/players/stormie_hero/model_luke.skin
- mb2_cmp_assets3/ext_data/npcs/drexl.npc
- mb2_cmp_assets3/ext_data/npcs/kotor_droids.npc
- mb2_cmp_assets3/models/players/KotorDroids/model_blue.skin
- mb2_cmp_assets3/models/players/KotorDroids/model_default.skin
- mb2_cmp_assets3/models/players/KotorDroids/model_t31.skin
- mb2_cmp_assets3/models/players/KotorDroids/model_t32.skin
- mb2_cmp_assets3/models/players/KotorDroids/model_t33.skin
- mb2_cmp_assets3/models/players/KotorDroids/modeldata.cfg
- mb2_cmp_assets3/models/players/rancor/model_drexl.skin
- mb2_cmp_assets3/shaders/KotorDroids.shader
- mb2_cmp_assets3/shaders/drexl.shader
Merging already tested/finished model assets.
> Model fa updates

- mb2_cmp_assets3/maps/mb2_cmp_onderon_beta.siege
> oops, forgot Onderon siege file

- mb2_cmp_assets3/ext_data/mb2/character/Arena_Barriss.mbch
- mb2_cmp_assets3/ext_data/mb2/character/Arena_C3P0.mbch
- mb2_cmp_assets3/ext_data/mb2/character/Arena_Eeth.mbch
- mb2_cmp_assets3/ext_data/mb2/character/Arena_Fisto.mbch
- mb2_cmp_assets3/ext_data/mb2/character/Arena_Joejedi1.mbch
- mb2_cmp_assets3/ext_data/mb2/character/Arena_Joejedi2.mbch
- mb2_cmp_assets3/ext_data/mb2/character/Arena_Kiadi.mbch
- mb2_cmp_assets3/ext_data/mb2/character/Arena_Luminara.mbch
- mb2_cmp_assets3/ext_data/mb2/character/Arena_Mace.mbch
- mb2_cmp_assets3/ext_data/mb2/character/Arena_Obi1.mbch
- mb2_cmp_assets3/ext_data/mb2/character/Arena_Padme.mbch
- mb2_cmp_assets3/ext_data/mb2/character/Arena_Plo.mbch
- mb2_cmp_assets3/ext_data/mb2/character/Arena_SBD1.mbch
- mb2_cmp_assets3/ext_data/mb2/character/Arena_SBD2.mbch
- mb2_cmp_assets3/ext_data/mb2/character/Arena_SBD3.mbch
- mb2_cmp_assets3/ext_data/mb2/character/Arena_Saesee.mbch
- mb2_cmp_assets3/ext_data/mb2/character/Arena_Shaak.mbch
- mb2_cmp_assets3/ext_data/mb2/character/Arena_Sora.mbch
- mb2_cmp_assets3/ext_data/mb2/character/Arena_Stass.mbch
- mb2_cmp_assets3/ext_data/mb2/character/Arena_Trebor.mbch
- mb2_cmp_assets3/ext_data/mb2/character/Arena_anakin.mbch
- mb2_cmp_assets3/ext_data/mb2/character/Arena_c3po2.mbch
- mb2_cmp_assets3/ext_data/mb2/character/Arena_dooku.mbch
- mb2_cmp_assets3/ext_data/mb2/character/Arena_droideka1.mbch
- mb2_cmp_assets3/ext_data/mb2/character/Arena_geo.mbch
- mb2_cmp_assets3/ext_data/mb2/character/Arena_geo2.mbch
Fixed and updated a number of descriptions, readded Push and Pull on Luminara based on description so she has something to use. Readded Deflect based on descriptions to several. QOL Changes to a number of characters to their descriptions.
> QOL Changes CMP_ARENA

- mb2_cmp_assets3/ext_data/mb2/character/mkeep_chewie.mbch
- mb2_cmp_assets3/ext_data/mb2/character/mkeep_commander.mbch
- mb2_cmp_assets3/ext_data/mb2/character/mkeep_han.mbch
- mb2_cmp_assets3/ext_data/mb2/character/mkeep_howler.mbch
- mb2_cmp_assets3/ext_data/mb2/character/mkeep_lando.mbch
- mb2_cmp_assets3/ext_data/mb2/character/mkeep_leia.mbch
- mb2_cmp_assets3/ext_data/mb2/character/mkeep_lobot.mbch
- mb2_cmp_assets3/ext_data/mb2/character/mkeep_luke.mbch
- mb2_cmp_assets3/ext_data/mb2/character/mkeep_officer.mbch
- mb2_cmp_assets3/ext_data/mb2/character/mkeep_sith1.mbch
- mb2_cmp_assets3/ext_data/mb2/character/mkeep_soldier.mbch
- mb2_cmp_assets3/ext_data/mb2/character/mkeep_storm.mbch
- mb2_cmp_assets3/ext_data/mb2/character/mkeep_swamp_jetpack.mbch
- mb2_cmp_assets3/ext_data/mb2/character/mkeep_swamp_scout.mbch
CMP_Mountainkeep
Added new character descriptions for several characters that didn't have one for their background as part of a QOL update for FA.
> New Descriptions for CMP_Mountainkeep

- MBAssets3/shaders/weapons2.shader
Fixed darktrooper gun shader (assault_cannon)
> weapons2.shader

- MBAssets3/ext_data/mb2/character/RC_cis_bdsniper.mbch
- MBAssets3/ext_data/mb2/character/Thed_bdsniper.mbch
- mb2_cmp_assets3/ext_data/mb2/character/geo_cmp_SBattleDroidSniper.mbch
- mb2_cmp_assets3/ext_data/mb2/character/theed2_XP.mbch
- mb2_cmp_assets3/ext_data/mb2/character/theed2_bd.mbch
- mb2_cmp_assets3/ext_data/mb2/character/theed2_bdcommand.mbch
- mb2_cmp_assets3/ext_data/mb2/character/theed2_bdelitetrooper.mbch
- mb2_cmp_assets3/ext_data/mb2/character/theed2_bdsniper.mbch
- mb2_cmp_assets3/ext_data/mb2/character/theed2_droideka.mbch
- mb2_cmp_assets3/ext_data/mb2/character/theed2_elitetrooper.mbch
- mb2_cmp_assets3/ext_data/mb2/character/theed2_jarjar.mbch
- mb2_cmp_assets3/ext_data/mb2/character/theed2_nute.mbch
- mb2_cmp_assets3/ext_data/mb2/character/theed2_obiwan.mbch
- mb2_cmp_assets3/ext_data/mb2/character/theed2_padme.mbch
- mb2_cmp_assets3/ext_data/mb2/character/theed2_quigon.mbch
- mb2_cmp_assets3/ext_data/mb2/character/theed2_sabe.mbch
- mb2_cmp_assets3/ext_data/mb2/character/theed2_sold.mbch
- mb2_cmp_assets3/ext_data/mb2/character/theed2_troopsniper.mbch
Updated B1 Droids with snipers to have the SOM3 Rifle (Sniper from OG BF) and changed the names to SOM3 in the descriptions.
> Droid Sniper Update

- MB_Effects/effects/Grenades/EXP_Conc.efx
- MB_Effects/effects/Grenades/EXP_Conc_E.efx
Note: GCJ stated this does not replace any base assets, so it should be good to go.
> Adding Duckshark's more accurate Conc Radius efx

- mb2_um_assets3/ext_data/mb2/character/nar_bluesniper.mbch
- mb2_um_assets3/ext_data/mb2/character/nar_redsniper.mbch
> UM NAR fa fix

- MBAssets3/ext_data/mb2/character/htk_rep_bastila.mbch
- MBAssets3/ext_data/mb2/character/htk_rep_canderous.mbch
- MBAssets3/ext_data/mb2/character/htk_rep_carth.mbch
- MBAssets3/ext_data/mb2/character/htk_rep_jolee.mbch
- MBAssets3/ext_data/mb2/character/htk_rep_juhani.mbch
- MBAssets3/ext_data/mb2/character/htk_rep_merc.mbch
- MBAssets3/ext_data/mb2/character/htk_rep_revan.mbch
- MBAssets3/ext_data/mb2/character/htk_rep_survivor.mbch
- MBAssets3/ext_data/mb2/character/htk_s_agressive.mbch
- MBAssets3/ext_data/mb2/character/htk_s_bandon.mbch
- MBAssets3/ext_data/mb2/character/htk_s_darkjedi.mbch
- MBAssets3/ext_data/mb2/character/htk_s_insane.mbch
- MBAssets3/ext_data/mb2/character/htk_s_manic.mbch
- MBAssets3/ext_data/mb2/character/htk_s_paranoid.mbch
- MBAssets3/ext_data/mb2/character/htk_s_scientist.mbch
- MBAssets3/ext_data/mb2/character/htk_s_sendroid1.mbch
- MBAssets3/ext_data/mb2/character/htk_s_sendroid2.mbch
- MBAssets3/ext_data/mb2/teamconfig/Hrakert_Republic.mbtc
- MBAssets3/ext_data/mb2/teamconfig/Hrakert_Selkath.mbtc
- MBAssets3/ext_data/npcs/firaxa.npc
- MBAssets3/ext_data/npcs/selkath_zombie.npc
- MBAssets3/maps/mb2_hrakertstation.siege
> Hrakert FA files

- MBAssets3/ext_data/npcs/probe.npc
- MBAssets3/maps/mb2_dotf_classicb.siege
moving hint icons up for dotf classicb so you can actually see enemies when looking that way
> dotf b hint icon tweak

- MBAssets3/ext_data/npcs/hutt.npc
- MBAssets3/ext_data/npcs/mus_wt.npc
- MBAssets3/ext_data/npcs/nexu.npc
- MBAssets3/ext_data/npcs/nute_gunray.npc
- MBAssets3/ext_data/npcs/wampa.npc
- MBAssets3/ext_data/npcs/wampa_base.npc
- MBAssets3/ext_data/npcs/wampa_jungle.npc
- MBAssets3/ext_data/npcs/younglings.npc
> reverting some of the npc hp buffs

- MBAssets3/models/players/chiss/modeldata.cfg
- MBAssets3/models/players/kreia/model_handless.skin
- MBAssets3/models/players/kreia/model_traya.skin
- mb2_cmp_assets3/ext_data/mb2/character/mkeep_leia.mbch
- Traya head decaps
- Human Bartender wrong soundset path
- proper Leia saber hilt on Mountain Keep FA
> Minor issue fixes recently reported

- mb2_um_assets3/ext_data/mb2/character/bf_t_homerun.mbch
- mb2_um_assets3/ext_data/mb2/character/bf_w_homerun.mbch
let's see if it works since my devmap is being disagreeable
> breakf concrifle3

- mb2_um_assets3/ext_data/mb2/character/bh_tb_gru.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tb_man.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tb_med.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tb_sbd.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tb_sni.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tb_sup.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tr_gru.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tr_man.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tr_med.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tr_sbd.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tr_sni.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tr_sup.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tr_wook.mbch
- mb2_um_assets3/ext_data/sabers/saber_projheaven.sab
+ other open beta feedback optimizations
> sbd has functioning wrist rocket (projheaven)

- mb2_um_assets3/ext_data/mb2/character/bh_tb_eng.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tb_gru.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tb_man.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tb_med.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tb_sbd.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tb_sco.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tb_sni.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tb_sup.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tb_wook.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tr_eng.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tr_gru.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tr_man.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tr_med.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tr_sbd.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tr_sco.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tr_sni.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tr_sup.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tr_wook.mbch
- mb2_um_assets3/ext_data/mb2/teamconfig/Proj_Blue.mbtc
- mb2_um_assets3/ext_data/mb2/teamconfig/Proj_Red.mbtc
- mb2_um_assets3/ext_data/sabers/saber_projheaven.sab
[PLEASE ADD THESE TGAS TO MODELS/PLAYERS/PROJHEAVEN](https://cdn.discordapp.com/attachments/455201821510729750/1269852404828864512/compressed_1.zip?ex=66b191b6&is=66b04036&hm=69ac062e4a26bbb5b39b21db9c1945db1cd887fc90eea95fda535fdd0d627c2c&)
> Projheaven upgrades & frenzy's ideas

- 03_MovieGameMappack/Effects/bow/muzzle.efx
- MBAssets3/ext_data/mb2/character/_H_A7_ClnJT.mbch
- MBAssets3/ext_data/mb2/character/_H_B2_Ewok.mbch
- MB_Effects/effects/stone/explosion.efx
disabling EMP muzzle and missile for now
readded ewok stone impact sound
> ewok and jump trooper efx fixes

- mb2_um_assets3/ext_data/mb2/character/bh_tb_eng.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tb_gru.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tb_man.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tb_med.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tb_sbd.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tb_sco.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tb_sni.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tb_sup.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tb_wook.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tr_eng.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tr_gru.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tr_man.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tr_med.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tr_sbd.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tr_sco.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tr_sni.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tr_sup.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tr_wook.mbch
- mb2_um_assets3/ext_data/sabers/saber_projheaven.sab
added in a lot more base models, ammo is generally lower, and requires upon grunts or ammo dispensers
added shock baton to scout
added imperial repeater and nerfed it
2shot proj to balance snipers against the uM additions & craziness
point buy is further balanced for some classes
snipers apply HELD_DISRUPTIFY to killed enemies, kill with class!
team heal is a bit more expensive to purchase for balance
> massive updates and balancing to projheaven

- mb2_um_assets3/ext_data/mb2/character/bh_tb_sup.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tr_sup.mbch
merged right on my last commit, but this is it
> gotta have kyle (proj heaven)

- mb2_um_assets3/ext_data/mb2/character/bh_tb_med.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tb_wook.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tr_med.mbch
- mb2_um_assets3/ext_data/mb2/character/bh_tr_wook.mbch
it was triggering my OCD and now the point buy isnt ugly
> cleaned up wookie point buy (proj heaven)

- mb2_um_assets3/ext_data/mb2/teamconfig/LOTA_Jedi_Blue.mbtc
- mb2_um_assets3/ext_data/mb2/teamconfig/LOTA_Jedi_Red.mbtc
by request of:
https://community.moviebattles.org/threads/capture-the-flag-sabers-only.10418/#post-101331
> jedi only siegeteams for LOTA bhop CTF

- MBAssets3/strings/English/HELP_TIPS.str
Selected tip edits for current patch.
> Update HELP_TIPS.str for r20.0.03

- mb2_um_assets3/ext_data/mb2/character/lota_tb_spy.mbch
- mb2_um_assets3/ext_data/mb2/character/lota_tr_spy.mbch
- mb2_um_assets3/ext_data/mb2/character/lotancl_tb_spy.mbch
- mb2_um_assets3/ext_data/mb2/character/lotancl_tr_spy.mbch
> adds hk droid models to spy class (lota)

- mb2_um_assets3/maps/mp/ctf1.siege
- mb2_um_assets3/maps/mp/ctf2.siege
- mb2_um_assets3/maps/mp/ctf3.siege
- mb2_um_assets3/maps/mp/ctf4.siege
- mb2_um_assets3/maps/mp/ctf5.siege
> fixes base jka ctf maps

- mb2_um_assets3/ext_data/mb2/character/lota_tb_hvy.mbch
- mb2_um_assets3/ext_data/mb2/character/lota_tr_hvy.mbch
- mb2_um_assets3/ext_data/mb2/character/lotancl_tb_hvy.mbch
- mb2_um_assets3/ext_data/mb2/character/lotancl_tr_hvy.mbch
for some reason you can't select blue heavy on either siegeteam, LOTA_Blue && LOTA_NCL_Blue
> lota_tb_hvy
EDIT: fixed, was above 81.9k character limit, by 82k.
> attempted heavy fix (LOTA)

- MBAssets3/ext_data/mb2/character/_V_B13_Nghri.mbch
Lowers idle cloak time from 45 to 25 seconds
> _V_B13_Nghri cloak resource > battery

- MBAssets3/shaders/mb_ui_automaps.shader
apparently this didnt work the first time
> dxun minimap fix

- mb2_um_assets3/ext_data/mb2/character/lota_tb_hvy.mbch
- mb2_um_assets3/ext_data/mb2/character/lota_tb_man.mbch
- mb2_um_assets3/ext_data/mb2/character/lota_tb_pist.mbch
- mb2_um_assets3/ext_data/mb2/character/lota_tb_sni.mbch
- mb2_um_assets3/ext_data/mb2/character/lota_tb_sup.mbch
- mb2_um_assets3/ext_data/mb2/character/lota_tb_wook.mbch
- mb2_um_assets3/ext_data/mb2/character/lota_tr_hvy.mbch
- mb2_um_assets3/ext_data/mb2/character/lota_tr_man.mbch
- mb2_um_assets3/ext_data/mb2/character/lota_tr_pist.mbch
- mb2_um_assets3/ext_data/mb2/character/lota_tr_sni.mbch
- mb2_um_assets3/ext_data/mb2/character/lota_tr_sup.mbch
- mb2_um_assets3/ext_data/mb2/character/lota_tr_wook.mbch
- mb2_um_assets3/ext_data/mb2/character/lotancl_tb_hvy.mbch
- mb2_um_assets3/ext_data/mb2/character/lotancl_tb_man.mbch
- mb2_um_assets3/ext_data/mb2/character/lotancl_tb_pist.mbch
- mb2_um_assets3/ext_data/mb2/character/lotancl_tb_sni.mbch
- mb2_um_assets3/ext_data/mb2/character/lotancl_tb_sup.mbch
- mb2_um_assets3/ext_data/mb2/character/lotancl_tb_wook.mbch
- mb2_um_assets3/ext_data/mb2/character/lotancl_tr_hvy.mbch
- mb2_um_assets3/ext_data/mb2/character/lotancl_tr_man.mbch
- mb2_um_assets3/ext_data/mb2/character/lotancl_tr_pist.mbch
- mb2_um_assets3/ext_data/mb2/character/lotancl_tr_sni.mbch
- mb2_um_assets3/ext_data/mb2/character/lotancl_tr_sup.mbch
- mb2_um_assets3/ext_data/mb2/character/lotancl_tr_wook.mbch
* heavy class has an increase of HP by +50, due to lack of armor without using actual combat shielding.
> (LOTA) final heavy updates this patch

- mb2_um_assets3/ext_data/mb2/character/lota_tb_sbd.mbch
- mb2_um_assets3/ext_data/mb2/character/lota_tr_sbd.mbch
- mb2_um_assets3/ext_data/mb2/character/lotancl_tb_sbd.mbch
- mb2_um_assets3/ext_data/mb2/character/lotancl_tr_sbd.mbch
* SBD has knockbackTaken 0 flags. Taking 0% knockback effect from HELD_KNOCKBACK damage.
> SBD is playable (LOTA) R20.09

- mb2_um_assets3/ext_data/mb2/character/lota_tb_eng.mbch
- mb2_um_assets3/ext_data/mb2/character/lota_tb_gru.mbch
- mb2_um_assets3/ext_data/mb2/character/lota_tb_hvy.mbch
- mb2_um_assets3/ext_data/mb2/character/lota_tb_man.mbch
- mb2_um_assets3/ext_data/mb2/character/lota_tr_eng.mbch
- mb2_um_assets3/ext_data/mb2/character/lota_tr_gru.mbch
- mb2_um_assets3/ext_data/mb2/character/lota_tr_hvy.mbch
- mb2_um_assets3/ext_data/mb2/character/lota_tr_man.mbch
- mb2_um_assets3/ext_data/mb2/character/lotancl_tb_eng.mbch
- mb2_um_assets3/ext_data/mb2/character/lotancl_tb_gru.mbch
- mb2_um_assets3/ext_data/mb2/character/lotancl_tb_hvy.mbch
- mb2_um_assets3/ext_data/mb2/character/lotancl_tb_man.mbch
- mb2_um_assets3/ext_data/mb2/character/lotancl_tr_eng.mbch
- mb2_um_assets3/ext_data/mb2/character/lotancl_tr_gru.mbch
- mb2_um_assets3/ext_data/mb2/character/lotancl_tr_hvy.mbch
- mb2_um_assets3/ext_data/mb2/character/lotancl_tr_man.mbch
* Heavy class now takes 0% knockback, due to it's slow speed just like the SBD.
* Heavy class now has 200 HP, HP was increased by +50.
* Heavy class now takes 10% less damage overall.
* Engineer point buy cleaned up furthermore, reduced by -30 points. E-11 given for free.
* Grunt class has reduction in points for point buy, by -50 points.
* Grunt class now has the ability to choose to assemble.
* Mandalorian class has forceregen of 2, to assist for replenishing of jetpack fuel.
> Lair of the Ancients changes R20.1

- MBAssets3/shaders/sbd.mtr
- MBAssets3/shaders/sbd.shader
> SBD Rend2 Text Assets

- MBAssets3/ext_data/mb2/character/Dxun_eh_HK47.mbch
- MBAssets3/ext_data/mb2/character/Dxun_eh_exile.mbch
- mb2_cmp_assets3/ext_data/mb2/character/ns_e_Exile.mbch
- mb2_cmp_assets3/ext_data/mb2/character/ns_e_HK47.mbch
- mb2_cmp_assets3/ext_data/mb2/character/ns_e_Handmaiden.mbch
- Meetra medium armor on both maps
- HK-47 rusty skin on both maps
- Brianna got jedi robes on NS, resulting in -1 full port
> Nar Shaddaa and Dxun skin path changes

- mb2_cmp_assets3/ext_data/mb2/character/grievous_magna.mbch
> For the Grievous Boss Battle FA on mb2_cmp_duel_palp
> Magnaguard no longer uses supremacy sounds (woopsie)

- MBAssets3/ui/mb/alpha/game/class/mb_class_jedi.menu
- MBAssets3/ui/mb/alpha/game/class/mb_class_sith.menu
> Adding saber thrown to card

- MBAssets3/ui/mb/alpha/game/class/mb_class_jedi.menu
- MBAssets3/ui/mb/alpha/game/class/mb_class_sith.menu
Adding CS1 to saber throw per leonss.
> Nnn saber throw

- MBAssets3/ui/mb/minimalismhud/hud/mb_hud.menu
- MBAssets3/ui/mb/minimalismhud/hud/mb_hud_centered_playerstatus.menu
- MBAssets3/ui/mb/minimalismhud/hud/mb_hud_chat.menu
- MBAssets3/ui/mb/minimalismhud/hud/mb_hud_playerstatus.menu
- MBAssets3/ui/mb/minimalismhud/hud/mb_hud_radar.menu
- MBAssets3/ui/mb/minimalismhud/hud/mb_hud_scoreboard.menu
- MBAssets3/ui/mb/minimalismhud/hud/mb_hud_specials.menu
- MBAssets3/ui/mb/minimalismhud/hud/mb_hud_teamkill.menu
- MBAssets3/ui/mb/minimalismhud/hud/mb_hud_teamoverlay.menu
- MBAssets3/ui/mb/minimalismhud/hud/mb_hud_timer.menu
- MBAssets3/ui/mb/minimalismhud/hud/mb_hud_voicechat.menu
huh missing minimalismhud folder
> fix minimalismhud

- z_MBLegends/ext_data/mb2/character/h3_CloneCom.mbch
> h2 > h3 clonecom

- MBAssets3/ui/mb/alpha/game/class/mb_class_clonetrooper.menu
- MBAssets3/ui/mb/hybrid/game/class/mb_class_clonetrooper.menu
> Nn2/clone UI

- MBAssets3/ext_data/npcs/assassin_droid.npc
- MBAssets3/ext_data/npcs/hordeCW.npc
- MBAssets3/ext_data/npcs/hordeKotor.npc
- MBAssets3/ext_data/npcs/remote_imp.npc
> Shock field and Horde NPCs

- MBAssets3/ext_data/npcs/cultistcommando.npc
- MBAssets3/ext_data/npcs/hordeCW.npc
- MBAssets3/ext_data/npcs/hordeKotor.npc
- MBAssets3/ext_data/npcs/remote_imp.npc
- MBAssets3/ext_data/npcs/saboteur.npc
- MBAssets3/ext_data/npcs/shadowtrooper.npc
- MBAssets3/ext_data/npcs/tavion_new.npc
- MBAssets3/ext_data/npcs/tusken.npc
> Resource fixes

- MBAssets3/ext_data/npcs/alora.npc
- MBAssets3/ext_data/npcs/cultist_destroyer.npc
- MBAssets3/ext_data/npcs/cultist_drain.npc
- MBAssets3/ext_data/npcs/cultist_grip.npc
- MBAssets3/ext_data/npcs/cultist_lightning.npc
- MBAssets3/ext_data/npcs/cultist_saber.npc
- MBAssets3/ext_data/npcs/cultist_saber_powers.npc
- MBAssets3/ext_data/npcs/desann.npc
- MBAssets3/ext_data/npcs/hordeSaber.npc
- MBAssets3/ext_data/npcs/jedi.npc
- MBAssets3/ext_data/npcs/jedif.npc
- MBAssets3/ext_data/npcs/jedimaster.npc
- MBAssets3/ext_data/npcs/jeditrainer.npc
- MBAssets3/ext_data/npcs/kyle.npc
- MBAssets3/ext_data/npcs/luke.npc
- MBAssets3/ext_data/npcs/reborn.npc
- MBAssets3/ext_data/npcs/reborn_dual.npc
- MBAssets3/ext_data/npcs/reborn_new.npc
- MBAssets3/ext_data/npcs/reborn_staff.npc
- MBAssets3/ext_data/npcs/reborn_twin.npc
- MBAssets3/ext_data/npcs/rebornacrobat.npc
- MBAssets3/ext_data/npcs/rebornboss.npc
- MBAssets3/ext_data/npcs/rebornfencer.npc
- MBAssets3/ext_data/npcs/rebornforceuser.npc
- MBAssets3/ext_data/npcs/rosh_penin.npc
- MBAssets3/ext_data/npcs/saber_droid.npc
- MBAssets3/ext_data/npcs/shadowtrooper.npc
- MBAssets3/ext_data/npcs/tavion.npc
- MBAssets3/ext_data/npcs/tavion_new.npc
Setting up Pbchance, MBchance, and SBchance values for base saber npcs.
> Adding values for sabering

- MBAssets3/ext_data/npcs/cultist_drain.npc
- MBAssets3/ext_data/npcs/cultist_grip.npc
- MBAssets3/ext_data/npcs/cultist_lightning.npc
- MBAssets3/ext_data/npcs/hordeCW.npc
- MBAssets3/ext_data/npcs/hordeKotor.npc
> setting up nade using npcs

- z_MBLegends/ext_data/sabers/saber_legends_other2.sab
> Revert "Update saber_legends_other2.sab"

- MBAssets3/ext_data/npcs/hordeCIS.npc
- MBAssets3/ext_data/npcs/hordeClones.npc
- MBAssets3/ext_data/npcs/hordeKotor.npc
- MBAssets3/ext_data/npcs/hutt.npc
- MBAssets3/ext_data/npcs/r2d2mb.npc
> Splitting up horde npcs
